[package]
name = "example"
version.workspace = true
edition.workspace = true
authors.workspace = true
default-run = "basic"
publish = false

[[bin]]
name = "basic"
path = "src/bin/basic.rs"

[[bin]]
name = "macros"
path = "src/bin/macros.rs"
required-features = ["macros"]

[[bin]]
name = "serde"
path = "src/bin/serde.rs"
required-features = ["serde_json"]

[[bin]]
name = "video_stream"
path = "src/bin/video_stream.rs"

[features]
default = []
macros = ["deltapatcher/macros"]
serde_json = ["dep:serde_json", "deltapatcher/serde"]

[dependencies]
rand = "0.10.2"
serde_json = { version = "1.0.151", optional = true }

[dependencies.deltapatcher]
workspace = true
