[workspace]
members = ["deltapatcher", "deltapatcher-macros", "example"]
resolver = "2"

[workspace.package]
version = "0.1.1"
edition = "2024"
authors = ["HyperCodec"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/HyperCodec/deltapatcher"
homepage = "https://github.com/HyperCodec/deltapatcher"
documentation = "https://docs.rs/deltapatcher"

[workspace.dependencies]
deltapatcher = { path = "deltapatcher", version = "0.1.1" }
deltapatcher-macros = { path = "deltapatcher-macros", version = "0.1.1" }
