use proc_macro::TokenStream;
use proc_macro2::{TokenStream as TokenStream2, Span};
use quote::quote;
use syn::{Data, DeriveInput, parse_macro_input};

use darling::{FromAttributes, FromDeriveInput};

/// Field-level config via attributes.
#[derive(FromAttributes)]
#[darling(attributes(deltapatcher))]
struct DiffFieldConfig {
    /// For fields with multiple candidate delta types,
    /// use this to specify the delta type to use.
    delta_ty: syn::Type,
}

/// Struct-level config via attributes.
#[derive(FromDeriveInput)]
#[darling(attributes(deltapatcher))]
struct DiffOverallConfig {
    delta_name: Option<syn::Ident>,
    delta_vis: Option<syn::Visibility>,
    delta_derive: Option<Vec<syn::Ident>>,
}

impl DiffOverallConfig {
    fn delta_name_or_default(&self, ty_name: &syn::Ident) -> syn::Ident {
        self.delta_name.clone().unwrap_or_else(|| syn::Ident::new(&format!("{ty_name}Delta"), Span::call_site()))
    }
}

// TODO doc comment
#[proc_macro_derive(Differentiable, attributes(deltapatcher))]
pub fn derive_differentiable(input: TokenStream) -> TokenStream {
    let ast = parse_macro_input!(input as DeriveInput);
    let top_level_config = DiffOverallConfig::from_derive_input(&ast).unwrap();

    match ast.data {
        Data::Enum(e) => differentiable_enum(ast.ident, e, top_level_config),
        Data::Struct(s) => differentiable_struct(ast.vis, ast.ident, s, top_level_config),
        Data::Union(u) => differentiable_union(ast.ident, u, top_level_config),
    }.unwrap_or_else(syn::Error::into_compile_error).into()
}

fn differentiable_enum(_ident: syn::Ident, _e: syn::DataEnum, _config: DiffOverallConfig) -> syn::Result<TokenStream2> {
    unimplemented!("enums not yet supported")
}

fn differentiable_struct(vis: syn::Visibility, ident: syn::Ident, s: syn::DataStruct, config: DiffOverallConfig) -> syn::Result<TokenStream2> {
    let mut delta_field_type = Vec::with_capacity(s.fields.len());
    for field in &s.fields {
        if let Ok(field_config) = DiffFieldConfig::from_attributes(&field.attrs) {
            delta_field_type.push(field_config.delta_ty);
        } else {
            return Err(syn::Error::new_spanned(field, "Cannot infer delta type. Field must be annotated with #[deltapatcher(delta_ty = SomeDelta)]."));
        }
    }

    let delta_name = config.delta_name_or_default(&ident);
    // TODO span for delta derive (i.e. highlight the arg when using invalid type)
    let delta_derive = config.delta_derive
        .map(|vals| quote! { #[derive(#(#vals),*)] })
        .unwrap_or(quote!{});
    let delta_vis = config.delta_vis.unwrap_or(vis);
    let delta_doc = format!("Autogenerated delta for struct [`{ident}`]");
    
    Ok(match s.fields {
        syn::Fields::Named(n) => {
            let field_vis = n.named.iter().map(|field| field.vis.clone());
            let field_name = n.named.iter().map(|f| f.ident.clone().unwrap()).collect::<Vec<_>>();
            let field_type = n.named.iter().map(|f| f.ty.clone()).collect::<Vec<_>>();

            quote! {
                #[doc = #delta_doc]
                #delta_derive
                #delta_vis struct #delta_name {
                    #(#field_vis #field_name: #delta_field_type),*
                }

                impl deltapatcher::delta::Delta for #delta_name {
                    fn aggregate(&mut self, next: &Self) {
                        #(<#delta_field_type as deltapatcher::delta::Delta>::aggregate(&mut self.#field_name, &next.#field_name);)*
                    }

                    fn aggregate_owned(&mut self, next: Self) {
                        #(<#delta_field_type as deltapatcher::delta::Delta>::aggregate_owned(&mut self.#field_name, next.#field_name);)*
                    }
                }

                impl deltapatcher::delta::Differentiable<#delta_name> for #ident {
                    fn differentiate(&self, initial: &Self) -> #delta_name {
                        #delta_name {
                            #(#field_name: <#field_type as deltapatcher::delta::Differentiable<#delta_field_type>>::differentiate(&self.#field_name, &initial.#field_name)),*
                        }
                    }
                    fn patch(&mut self, delta: &#delta_name) {
                        #(<#field_type as deltapatcher::delta::Differentiable<#delta_field_type>>::patch(&mut self.#field_name, &delta.#field_name);)*
                    }
                }
            }
        },
        syn::Fields::Unnamed(un) => {
            let field_vis = un.unnamed.iter().map(|field| field.vis.clone());
            let field_idx = (0..un.unnamed.len()).collect::<Vec<_>>();
            let field_type = un.unnamed.iter().map(|f| f.ty.clone()).collect::<Vec<_>>();

            quote! {
                #[doc = #delta_doc]
                #delta_derive
                #delta_vis struct #delta_name(#(#field_vis #delta_field_type),*);

                impl deltapatcher::delta::Delta for #delta_name {
                    fn aggregate(&mut self, next: &Self) {
                        #(<#delta_field_type as deltapatcher::delta::Delta>::aggregate(&mut self.#field_idx, &next.#field_idx);)*
                    }

                    fn aggregate_owned(&mut self, next: Self) {
                        #(<#delta_field_type as deltapatcher::delta::Delta>::aggregate_owned(&mut self.#field_idx, next.#field_idx);)*
                    }
                }

                impl deltapatcher::delta::Differentiable<#delta_name> for #ident {
                    fn differentiate(&self, initial: &Self) -> #delta_name {
                        #delta_name (#(<#field_type as deltapatcher::delta::Differentiable<#delta_field_type>>::differentiate(&self.#field_idx, &initial.#field_idx)),*)
                    }
                    fn patch(&mut self, delta: &#delta_name) {
                        #(<#field_type as deltapatcher::delta::Differentiable<#delta_field_type>>::patch(&mut self.#field_idx, &delta.#field_idx);)*
                    }
                }
            }
        },
        syn::Fields::Unit => {
            // unit struct, implement no-op

            quote! {
                #[doc = #delta_doc]
                #delta_derive
                #delta_vis struct #delta_name;

                impl deltapatcher::delta::Delta for #delta_name {
                    fn aggregate(&mut self, _next: &Self) {}
                    fn aggregate_owned(&mut self, _next: Self) {}
                }

                impl deltapatcher::delta::Differentiable<#delta_name> for #ident {
                    fn differentiate(&self, _initial: &Self) -> #delta_name { #delta_name }
                    fn patch(&mut self, _delta: &#delta_name) {}
                }
            }
        },
    }.into())
}

fn differentiable_union(_ident: syn::Ident, _u: syn::DataUnion, _config: DiffOverallConfig) -> syn::Result<TokenStream2> {
    unimplemented!("unions not yet supported")
}