use proc_macro::TokenStream;
use proc_macro2::Span;
use quote::quote;
use syn::{Data, DeriveInput, parse_macro_input};

use darling::{FromAttributes, FromDeriveInput};

/// Field-level config via attributes.
#[derive(FromAttributes)]
#[darling(attributes(deltapatcher))]
struct DiffFieldConfig {
    /// For fields with multiple candidate delta types,
    /// use this to specify the delta type to use.
    delta_ty: syn::Type,
}

/// Struct-level config via attributes.
#[derive(FromDeriveInput)]
#[darling(attributes(deltapatcher))]
struct DiffOverallConfig {
    delta_name: Option<syn::Ident>,
    delta_vis: Option<syn::Visibility>,
    delta_derive: Option<Vec<syn::Ident>>,
}

impl DiffOverallConfig {
    fn delta_name_or_default(&self, ty_name: &syn::Ident) -> syn::Ident {
        self.delta_name.clone().unwrap_or_else(|| syn::Ident::new(&format!("{ty_name}Delta"), Span::call_site()))
    }
}

// TODO doc comment
#[proc_macro_derive(Differentiable, attributes(deltapatcher))]
pub fn derive_differentiable(input: TokenStream) -> TokenStream {
    let ast = parse_macro_input!(input as DeriveInput);
    let top_level_config = DiffOverallConfig::from_derive_input(&ast).unwrap();

    match ast.data {
        Data::Enum(e) => differentiable_enum(ast.ident, e, top_level_config),
        Data::Struct(s) => differentiable_struct(ast.ident, s, top_level_config),
        Data::Union(u) => differentiable_union(ast.ident, u, top_level_config),
    }
}

fn differentiable_enum(ident: syn::Ident, e: syn::DataEnum, config: DiffOverallConfig) -> TokenStream {
    unimplemented!("enums not yet supported")
}

fn differentiable_struct(ident: syn::Ident, s: syn::DataStruct, config: DiffOverallConfig) -> TokenStream {
    let delta_field_type = s.fields.iter().map(|field| {
        // TODO error message "help" that tells users to do #[deltapatcher(delta_ty = Foo)] on fields
        let field_config = DiffFieldConfig::from_attributes(&field.attrs).unwrap();
        field_config.delta_ty
    }).collect::<Vec<_>>();

    let config_references_delta = config.delta_name.is_some() || config.delta_derive.is_some() || config.delta_vis.is_some();

    let delta_name = config.delta_name_or_default(&ident);
    // TODO span for delta derive (i.e. highlight the arg when using invalid type)
    let delta_derive = config.delta_derive
        .map(|vals| quote! { #[derive(#(#vals),*)] })
        .unwrap_or(quote!{});
    let delta_vis = config.delta_vis.unwrap();
    
    match s.fields {
        syn::Fields::Named(n) => {
            let field_vis = n.named.iter().map(|field| field.vis.clone());
            let field_name = n.named.iter().map(|f| f.ident.clone().unwrap()).collect::<Vec<_>>();
            let field_type = n.named.iter().map(|f| f.ty.clone()).collect::<Vec<_>>();

            quote! {
                #[doc = concat!("Autogenerated delta for struct [`", #ident, "`]")]
                #delta_derive
                #delta_vis struct #delta_name {
                    #(#field_vis #field_name: #delta_field_type),*
                }

                impl deltapatcher::delta::Delta for #delta_name {
                    fn aggregate(&mut self, next: &Self) {
                        #(<#delta_field_type as deltapatcher::delta::Delta>::aggregate(&mut self.#field_name, &next.#field_name);)*
                    }

                    fn aggregate_owned(&mut self, next: Self) {
                        #(<#delta_field_type as deltapatcher::delta::Delta>::aggregate_owned(&mut self.#field_name, &next.#field_name);)*
                    }
                }

                impl deltapatcher::delta::Differentiable<#delta_name> for #ident {
                    fn differentiate(&self, initial: &Self) -> #delta_name {
                        #delta_name {
                            #(#field_name: <#field_type as deltapatcher::delta::Differentiable<#delta_field_type>>::differentiate(&self.#field_name, &initial.#field_name)),*
                        }
                    }
                    fn patch(&mut self, delta: ref #delta_name) {
                        #(<#field_type as deltapatcher::delta::Differentiable<#delta_field_type>>::patch(&mut self.#field_name, &delta.#field_name);)*
                    }
                }
            }
        },
        syn::Fields::Unnamed(un) => {
            todo!()
        },
        syn::Fields::Unit => {
            // unit struct, implement no-op
            if config_references_delta {
                // TODO attribute span or turn into deadcode warning
                panic!("Delta types are not defined for unit structs");
            }

            quote! {
                impl deltapatcher::delta::Differentiable<()> for #ident {
                    fn differentiate(&self, _initial: &Self) -> () {}
                    fn patch(&mut self, _delta: &()) {}
                }
            }
        },
    }.into()
}

fn differentiable_union(ident: syn::Ident, u: syn::DataUnion, config: DiffOverallConfig) -> TokenStream {
    unimplemented!("unions not yet supported")
}