[package]
name = "deltapatcher-macros"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "Procedural macros for the deltapatcher crate."
keywords = ["delta", "diff", "patch", "derive", "macros"]
categories = ["data-structures", "development-tools::procedural-macro-helpers"]
publish = true

[lib]
proc-macro = true

[dependencies]
darling = "0.24.1"
proc-macro2 = "1.0.107"
quote = "1.0.47"
syn = "3.0.4"
